name: Report Broken Package
description: Report a package thats not installing.
title: "[BROKEN]: "
labels: ["broken", "packages"]
assignees:
  - hudsonm62
body:
  - type: markdown
    attributes:
      value: |
        Please check to see if this already exists in [Issues](https://github.com/hudsonm62/ChocoCommunity-Packages/issues).

        When writing out the details, please ensure you are writing it as if you were explaining it to somebody else, even if you will be working on and resolving the issue yourself. This helps others to understand the reasons for the issue and for it to be searchable in the future.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Ensure you have done the following before proceeding:"
      options:
        - label: Tested on the latest version of Chocolatey.
          required: true
        - label: Ensured this isn't a transient (limited to your current environment).
          required: true
        - label: Checked the [issue](https://github.com/hudsonm62/ChocoCommunity-Packages/issues) doesn't exist.

  - type: input
    id: package-id
    attributes:
      label: Package ID
      description: "Tip: It's the same name you use when downloading via `choco install`"
      placeholder: git
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What You Are Seeing?
      description: Also tell us, what did you expect to happen?
      placeholder: "An install failed! It should have worked!"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Verbose Logs
      value: choco install pkg-id --yes --verbose --debug
      placeholder: choco install pkg-id --yes --verbose --debug
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code. You can execute `choco install pkg-id --yes --verbose --debug` to get this, and/or from `chocolatey.log`.
      render: shell
    validations:
      required: true

  - type: textarea
    id: machine-info
    attributes:
      label: System Information
      description: Any relevant information about your running OS and machine/host. You can find the most of this under `Settings > System > About`.
      placeholder: |
        - Hyper-V Gen 1 VM
        - Windows 10 Pro x64 Build 19045.4957
        - Chocolatey v2.3.0
        - PS Core 7 & PS Desktop 5.1
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Any other information here that you feel may be relevant.
      placeholder: The more the merrier.
    validations:
      required: false
